# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

# Environment variables required:
# - PYPI_USER / PYPI_PASS: for publishing package to PyPi

version: 2


references:

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  save_repo: &save_repo
    save_cache:
      key: v1-repo-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/project     

jobs:

  build_and_test_37:
    docker:
      - image: circleci/python:3.7
    steps:  
      - *restore_repo
      - checkout
      - *save_repo
      - restore_cache:
          keys: 
            - v1-dependencies37-{{ checksum "requirements.txt"}}
            - v1-dependencies37        
      - run: |
            pip install virtualenv
            virtualenv ~/venv37
            . ~/venv37/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install .
            cd test
            pytest -v --cov awsutils --cov-report term-missing
      - save_cache:
          key: v1-dependencies37-{{ checksum "requirements.txt"}}
          paths:
            - ~/venv37

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - *restore_repo
      - restore_cache:
          keys: 
            - v1-dependencies37-{{ checksum "requirements.txt"}}
            - v1-dependencies37
      - run:
          name: Deploy
          command: |
            . ~/venv37/bin/activate
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            pip install twine
            python setup.py sdist
            VERSION=`awk -F\' '{print $2,$4}' awsutils/version.py`
            git tag $VERSION
            git push origin $VERSION
            twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" dist/*


workflows:
  version: 2
  build_test_37:
    jobs:
      - build_and_test_37
      - deploy:
          requires:
            - build_and_test_37
          filters:
            branches:
              only: master
